version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      cargo-patch-and-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: dtolnay/rust-toolchain
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      action-patch-and-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
